In [1]:
import pandas as pd


In [3]:
csv = pd.read_csv("edg1.csv")
print(csv.head())

               ban  camp            game_time  is_win  kill           op_ban  \
0  125|152|154|509     2  2019-01-12 21:43:10       0    16  162|187|189|507   
1  118|152|171|184     1  2019-01-12 21:15:22       1    12  162|189|198|507   
2  118|134|154|509     2  2019-01-12 20:37:50       1    14  129|141|162|189   
3  118|134|196|509     1  2019-01-12 19:54:48       0     4  140|162|189|507   
4  118|148|152|509     2  2019-01-12 19:22:20       0    15  140|171|186|189   

  op_camp op_kill              op_pick  op_team_id op_team_name  \
0    op_1   op_13  108|118|134|194|199          45       Hero久竞   
1    op_2    op_2  106|123|132|139|191          45       Hero久竞   
2    op_1    op_1  113|128|176|186|196          45       Hero久竞   
3    op_2   op_10  312|135|168|198|502          45       Hero久竞   
4    op_1   op_21  126|157|162|187|507          45       Hero久竞   

                  pick  season_id season_name  
0  129|132|149|156|168         22   2018冬季冠军杯  
1  135|141|193|196|5

In [4]:
print(csv['op_pick'].head())

0    108|118|134|194|199
1    106|123|132|139|191
2    113|128|176|186|196
3    312|135|168|198|502
4    126|157|162|187|507
Name: op_pick, dtype: object


In [5]:
print(type(csv['op_pick']))

<class 'pandas.core.series.Series'>


In [6]:
content_list = csv['op_pick']

In [10]:
with open('op_pick1.csv','a') as f:
    for content in content_list:
        f.write(content)
        f.write('\n')

In [15]:
dataset = pd.read_csv('op_pick1.csv')


TypeError: 'type' object is not subscriptable

In [17]:
print(list(dataset['pick1']))

[108, 106, 113, 312, 126, 129, 105, 105, 118, 125, 126, 113, 132, 111, 113, 125, 121, 111, 106, 111, 123, 132, 120, 125, 139, 129, 118, 135, 106, 105, 144, 118, 126, 134, 113, 105, 106, 126, 118, 123, 137, 125, 118, 113, 126, 134, 118, 118, 134, 154, 113, 118, 118, 126, 123, 132, 139, 106, 125, 126, 125, 125, 125, 106, 113, 123, 129, 126, 129, 134, 126, 125, 125, 134, 105, 134, 154, 117, 136, 120, 135, 120, 126]


In [18]:
print(dataset)

    pick1  pick2  pick3  pick4  pick5
0     108    118    134    194    199
1     106    123    132    139    191
2     113    128    176    186    196
3     312    135    168    198    502
4     126    157    162    187    507
5     129    174    182    189    510
6     105    118    123    125    502
7     105    126    154    176    502
8     118    132    154    171    510
9     125    132    153    193    194
10    126    132    141    171    510
11    113    123    156    167    510
12    132    135    156    186    507
13    111    118    126    184    198
14    113    128    140    176    502
15    125    144    174    189    510
16    121    152    162    171    194
17    111    140    154    171    507
18    106    120    186    502    510
19    111    118    123    186    509
20    123    152    168    502    510
21    132    152    186    507    509
22    120    154    162    182    183
23    125    126    148    183    510
24    139    144    179    191    502
25    129   

In [30]:
import numpy as np
data = np.array(dataset).reshape(-1, 5)

In [24]:
print(data)

[[[108]
  [118]
  [134]
  [194]
  [199]]

 [[106]
  [123]
  [132]
  [139]
  [191]]

 [[113]
  [128]
  [176]
  [186]
  [196]]

 [[312]
  [135]
  [168]
  [198]
  [502]]

 [[126]
  [157]
  [162]
  [187]
  [507]]

 [[129]
  [174]
  [182]
  [189]
  [510]]

 [[105]
  [118]
  [123]
  [125]
  [502]]

 [[105]
  [126]
  [154]
  [176]
  [502]]

 [[118]
  [132]
  [154]
  [171]
  [510]]

 [[125]
  [132]
  [153]
  [193]
  [194]]

 [[126]
  [132]
  [141]
  [171]
  [510]]

 [[113]
  [123]
  [156]
  [167]
  [510]]

 [[132]
  [135]
  [156]
  [186]
  [507]]

 [[111]
  [118]
  [126]
  [184]
  [198]]

 [[113]
  [128]
  [140]
  [176]
  [502]]

 [[125]
  [144]
  [174]
  [189]
  [510]]

 [[121]
  [152]
  [162]
  [171]
  [194]]

 [[111]
  [140]
  [154]
  [171]
  [507]]

 [[106]
  [120]
  [186]
  [502]
  [510]]

 [[111]
  [118]
  [123]
  [186]
  [509]]

 [[123]
  [152]
  [168]
  [502]
  [510]]

 [[132]
  [152]
  [186]
  [507]
  [509]]

 [[120]
  [154]
  [162]
  [182]
  [183]]

 [[125]
  [126]
  [148]
  [183]
  

In [44]:
import sys
sys.path.append(r'../apriori')
# python 原有apriori.py 文件故需要少些最后一个字母
import aprior
print(aprior.apriori(data,min_support = 0.09))

{frozenset({134}): 0.21686746987951808, frozenset({194}): 0.18072289156626506, frozenset({199}): 0.1686746987951807, frozenset({118}): 0.1566265060240964, frozenset({132}): 0.2289156626506024, frozenset({139}): 0.0963855421686747, frozenset({123}): 0.12048192771084337, frozenset({176}): 0.1566265060240964, frozenset({186}): 0.13253012048192772, frozenset({168}): 0.10843373493975904, frozenset({502}): 0.14457831325301204, frozenset({162}): 0.2289156626506024, frozenset({126}): 0.21686746987951808, frozenset({510}): 0.1686746987951807, frozenset({182}): 0.0963855421686747, frozenset({189}): 0.12048192771084337, frozenset({125}): 0.1927710843373494, frozenset({154}): 0.26506024096385544, frozenset({171}): 0.14457831325301204, frozenset({156}): 0.0963855421686747, frozenset({140}): 0.1566265060240964, frozenset({120}): 0.10843373493975904, frozenset({154, 199}): 0.0963855421686747, frozenset({162, 134}): 0.0963855421686747}


In [ ]:
# 我取最后两个组合，对此王者官网确定，确定（154，花木兰），（199，公孙离），（162，鸟人），（134，达摩）
# 这次的数据较少，只体现了edg在2018冬季冠军杯最喜欢的两队组合是（花木兰，公孙离）和（达摩，鸟人）